// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyASW1O4JQNHmDBkcL7rgYuUjKx2ba8jjhg',
    appId: '1:872034986522:web:dbb2d46616b5248fc1ffa3',
    messagingSenderId: '872034986522',
    projectId: 'ascend-e8fa0',
    authDomain: 'ascend-e8fa0.firebaseapp.com',
    databaseURL: 'https://ascend-e8fa0-default-rtdb.firebaseio.com',
    storageBucket: 'ascend-e8fa0.firebasestorage.app',
    measurementId: 'G-EH1E9R94CS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBppYL8ePBKTi1rsWBAB0iTB-pAuci9Sq4',
    appId: '1:872034986522:android:1a75015d26d387acc1ffa3',
    messagingSenderId: '872034986522',
    projectId: 'ascend-e8fa0',
    databaseURL: 'https://ascend-e8fa0-default-rtdb.firebaseio.com',
    storageBucket: 'ascend-e8fa0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh_O90OYXbrLgQlCAvGJKQjDy-VmUXrcY',
    appId: '1:872034986522:ios:6eaad0ac3ee4960ec1ffa3',
    messagingSenderId: '872034986522',
    projectId: 'ascend-e8fa0',
    databaseURL: 'https://ascend-e8fa0-default-rtdb.firebaseio.com',
    storageBucket: 'ascend-e8fa0.firebasestorage.app',
    iosBundleId: 'com.example.ascend',
  );
}
